### ISSUE TITLE
"vue-i18n/types/index" has no exported member 'LocaleMessageObject'

### ISSUE THREAD

**Issue by lucuza** [mrellipse/toucan#11]
First of all thanks for sharing this project. I got a place to start reading on how things are getting done.

I didn't manage to run the project successfully though. I get the following error: 
 
> (2,10): error TS2305: Module '"project/src/ui/node_modules/vue-i18n/types/index"' has no exported member 'LocaleMessageObject'

A simple search will lead to [this](https://github.com/kaorun343/vue-property-decorator/issues/13). But this option is already used. 

Another solution would be to upgrade to vue-i18n:7.3.3 according to [this](https://github.com/kazupon/vue-i18n/issues/250).

None of them worked. Is it only me?

**Comment by mrellipse** [comment]
thanks for letting me know about this! 👍 

it is a clear bug in dependencies. the project code is targeting type definitions that shipped with vue-i18n@7.3.2.

changes that occurred in vue-i18n@7.3.3 have broken it. for a quick fix

* delete /src/ui/node_modules/vue-i18n
* update /src/ui/package.json to explicitly use 7.3.2 for vue-i18n
* npm install

you should then be able to run webpack okay!

**Comment by mrellipse** [comment]
okay problem fixed now. i have patched the repo, and then updated and re-published the yeoman  generator project to npmjs

i hope you find the project a useful starter for building your site!
