### ISSUE TITLE
Please do some updates

### ISSUE THREAD

**Issue by hmuhdkamran** [mrellipse/toucan#12]
it is very essential to have pop-up just like "https://github.com/stoodz/vuejsTimer.git", I have integrated like if the user click on stay the token is updated with new expiry time.
second role based menu or features like 'https://aspnetboilerplate.com/Templates' would be beneficial.
separate layout for login and logged-in pages.
unit test for vue components should be added, like karma i.e 'https://vuejs.org/v2/guide/unit-testing.html'
repository based db integration should be integrated, I have done it and happy to share.
date time filter should be integrated as vue v-model integrated with date but need work around.

**Comment by hmuhdkamran** [comment]
Resolve the issue just making some ultration in webpack.config.js
`const plateform = process.platform;
    var config = webpackBase(outputPath, srcPath, '/dist/');
    if(plateform.indexOf('win') === -1) {
        config = webpackBase(outputPath, srcPath, '/');
    }`
and rename folder `Resources` to `resource`.

**Comment by mrellipse** [comment]
some of those are quite good ideas. I have am very busy at work lately though, but will definitely add a good number of them in the near future

could you please describe the date time filter idea in more detail? that is the only one I am not clear on. if you could take the time to do a gist, or even just some psuedo-code so I can understand, that would be helpful!

**Comment by hmuhdkamran** [comment]
suppose we are binding date and time variable with `<input type="date" v-model="dob"/>", when you set the 'dob = new Date(), dob = Date.Now' or get from db the control doesn't populate the value, you have to use momet for this purpose. if the engine use its own or customized filter it will be fantastic,

**Comment by hmuhdkamran** [comment]
You will get pretty good idea from 
`<div id="box">
   <input type="date" v-model="form.date2">
   <span>{{form.date2}}</span>
 </div>`

`var box = new Vue({
	el:'#box',
  data:{
  	form:{
      date2 : new Date()
      }
	}
});`

This will explain what I am trying to say

**Comment by mrellipse** [comment]
ok, thanks for that code, gives me a better idea of the problem being solved.

 i will break down your original request into multiple issues, and add them to a new project board for actioning.

**Comment by mrellipse** [comment]
Okay, i have done this now. A good number of them you will see come through in the future.

Two I won't be taking on board are 

* repositories in dotnetcore code : it's fairly easy to implement that pattern if people want to add it themselves. and I personally don't use it myself, as it adds overhead 
* role-driven menus : I can understand why this is appropriate, but not adding it to the list straight away data-driven roles that can be created by power users are very common place. If I get the time later in the year though, will action it!
