### ISSUE TITLE
Date Binding for Vue Components

### ISSUE THREAD

**Issue by mrellipse** [mrellipse/toucan#17]
> date time filter should be integrated as vue v-model integrated with date but need work around

> suppose we are binding date and time variable with `", when you set the 'dob = new Date(), dob = Date.Now' or get from db the control doesn't populate the value, you have to use moment.js for this purpose. if the engine use its own or customized filter it will be fantastic,

look at the following link and made the mentioned changes, you will understand
https://jsfiddle.net/jnash21/mzx7n1sq/ and change date2 : '2017-07-04' to date2 : new Date()

**Comment by mrellipse** [comment]
created a custom directive and published as a separate npm package [vue-model-date](https://www.npmjs.com/package/vue-model-date) for the purpose of handling binding to dates.

it relies on an alpha release of date-fns@2 - once this has been released, I will update this library, and also create one for working with time portion of dates.

**Comment by hmuhdkamran** [comment]
Done
