### ISSUE TITLE
Upgrade from Beta to Release of Bootstrap 4

### ISSUE THREAD

**Issue by mrellipse** [mrellipse/toucan#18]

**Comment by bjammin** [comment]
Just a note for when this gets done.  Bootstrap 4 beta seems to deprecate use of _custom.scss and it doesn't seem to work in this project.  So when release is added please ensure there is a way of adding custom variable values without modifying the core files.
Reference:
https://stackoverflow.com/questions/45651432/bootstrap-4-scss-overrides-not-working

Thanks!

**Comment by bjammin** [comment]
Also it would be really handy to implement bootstrap-vue as none of the bootstrap javascript components work currently (eg. the nav in mobile mode)

https://bootstrap-vue.js.org/

**Comment by mrellipse** [comment]
ah, it's now vue-bootstrap@4

I didn't expect bootstrap 4 to be in alpha for so long! so I held off adding bootstrap-vue until v4 was official

you asked about making pull requests before ... would you be willing to contribute one for vue-bootstrap? it's a pretty substantial piece of work to ask for, but github can offer you many fake internet points in return ;)

**Comment by bjammin** [comment]
I'd certainly be willing, but I'm such a noob with vue and the whole webpack process.  I'm not even sure how to [get started](https://bootstrap-vue.js.org/docs).

If you could point me in the right direction and give me a few notes I'd be happy to have a go.

**Comment by mrellipse** [comment]
:+1

no guts no glory.

alrighty, i will do some research and drop you an email! webpack can definitely be intimidating at first - but it's basically just a series of input/output pipes. You configure each step in the chain to filter the data inputs, operate on the selected inputs/files, and then produce one (or many) new outputs.

**Comment by mrellipse** [comment]
hi again!. just thought I would drop you a quick email to let you know i
haven't forgotten about this.

between work, family, kids and commuting, i get a bit time poor.

will try and spend some time on this today - I had a quick look on sunday,
and getting bootstrap-vue integrated with webpack shouldn't be too much of
an ask!

**Comment by mrellipse** [comment]
okay, i have done a review, and the following steps should get things
underway


   - clone the project from development
   - update the ui project dependencies for popper and bootstrap
   - add bootstrap-vue to dependencies
   - install dependencies
   - add 'bootstrap-vue' to the entry point for vendors bundle
   (webpack.config.js line 113)
   - import and register bootstrap-vue
   - debug!

once above is okay, the real work can get underway. that is, redoing the
forms and components to take advantage of model-binding and events exposed
by bootstrap-vue.

the bootstrap/sass compilation should be okay - webpack loaders are already
configured for dev and production builds - so I am pretty confident that
will work 'as is'.

let me know if you have any hassles!

:+1

cheers

**Comment by bjammin** [comment]
Thanks very much for looking into this.  I'm away from work for the next 1.5 weeks so won't have a chance to look at this until then, but I certainly will!

**Comment by hmuhdkamran** [comment]
I have done it, and it work flawlessly, I have also integrated Metronic 5, looking nice

**Comment by mrellipse** [comment]
superceded by plans for v3 release. no longer current issue.
