### ISSUE TITLE
HMR Failures

### ISSUE THREAD

**Issue by timg1474392** [mrellipse/toucan#2]
The response from a call such as http://localhost:5000/64ef3ad1b9684d6b00d8.hot-update.json

Is being intercepted/handled by custom middleware, and returning html instead of a hmr payload.

Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.request.onreadystatechange (common.js:77)

**Comment by mrellipse** [comment]
resolved in [v2.0.4](https://github.com/mrellipse/toucan/releases/tag/v2.0.4)
