### ISSUE TITLE
Role Based Menu

### ISSUE THREAD

**Issue by hmuhdkamran** [mrellipse/toucan#5]
I am using Toucan and adding the feature of Role base menu, but I am unable to work it. I have used the following steps.

1. Created an Interface for menu
`export interface IMenu { name: string; url: string; icon: string; children: IMenu[] }`
2. Then in types.ts I add `updateUserMenu: 'updateUserMenu'`,
3. In mutation.ts  I add
`updateUserMenu: (state: ICommonState, userMenu: Array<IMenu>) => { let user = Object.assign({}, state.user); user.userMenu = userMenu; state.user = user; }`
4. In action.ts I added
`updateUserMenu: (injectee: ActionContext<ICommonState, any>, userMenu: Array<IMenu>) => { injectee.commit(StoreTypes.updateUserMenu, userMenu); }`
and in login.ts I add
`this.repo.getMenu(this.username) .then((value) => this.$store.dispatch(StoreTypes.updateUserMenu, value));`
after
`this.auth.login(credentials) .then((value) => this.$store.dispatch(StoreTypes.updateUser, value)) .then(() => this.$store.dispatch(StoreTypes.updateStatusBar, null)) .then(() => this.$router.push(returnUrl)) .catch((user) => { });`
5. In sidebar.ts I call `@State((state: IRootStoreState) => state.common.user) user: IUser;`
6. In sidebar.html I use `(item, index) in user.userMenu`,
I didn't get any thing, nor calling the API.
Help Me out.

**Comment by mrellipse** [comment]
Based on above it looks like you have created Vuex store actions okay (1-3), and the sidebar binding looks okay (5-6).  I am thinking it might be an issue in the promises chain (4) in login component.

Does the code in action.ts look something like this?
```ts
        this.auth.login(credentials)
            .then((value) => this.$store.dispatch(StoreTypes.updateUser, value))
            .then(() => this.repo.getMenu(this.username))
            .then(value => this.$store.dispatch(StoreTypes.updateUserMenu, value))
            .then(() => this.$store.dispatch(StoreTypes.updateStatusBar, null))
            .then(() => this.$router.push(returnUrl))
            .catch(() => { });
```
The first step is definitely to make sure your call to repo service is being invoked, by looking at network activity in browser dev tools.

Also, have you tried installing [Vue.js devtools](https://addons.mozilla.org/en-US/firefox/addon/vue-js-devtools/) ? It's really helpful for inspecting both Vue and Vuex state data!

**Comment by hmuhdkamran** [comment]
Thanks allot. It did the trick. now one thing more.
how to intimate server that the token is not expired if the user is working on client, or if the token is expired   on server side the client redirect to login.
