### ISSUE TITLE
Add SignalR to sync

### ISSUE THREAD

**Issue by hmuhdkamran** [mrellipse/toucan#6]
Add SignalR to sync both side, when the token is expired on server side vice versa, the system should logout.
If the client is working on a page and the token on server side is expired the client should intimate the server that user is currently working and should not be logged out.

**Comment by mrellipse** [comment]
Hi there, sorry about the delay in replying. Work has been crazy past few days!

If you view [token-helper.ts#L61](https://github.com/mrellipse/toucan/blob/83fb5341eee64f9702af059b729d2ee273c02d64/src/ui/app/common/token-helper.ts#L61) you can see that client code already has access to the date & time when the token will expire 

I am thinking that a much simpler way would be if you created a Vue component, that binds to the user object in the Vuex store, and does countdown checks 😄 

I don't want to add SignalR as the Toucan template is already opinionated enough. I deliberately left out a lot of things such as logging, lodash - people want to do these in different ways.
