### ISSUE TITLE
add ui widget to track when access token is about to expire

### ISSUE THREAD

**Issue by timg1474392** [mrellipse/toucan#7]
add oauth refresh tokens server-side
add client-side code to prompt the user to refresh
do an in-place update of local storage and vuex state when refresh token is obtained

**Comment by mrellipse** [comment]
forgot it was using implicit authorization workflow, so refresh tokens are not issued.

better to extend the access token ttl, and just advise the user when/if their token expires

**Comment by hmuhdkamran** [comment]
Async token expiration or token expiration intimation is essential.

**Comment by mrellipse** [comment]
okay, i have added in a simple client-side widget which will server this purpose.

it uses the existing vuex state to push info/alert/error style messages via javascript timeouts

there is also an optional boolean value (defaults to true) which pushes users to login route

* when token expires during an active session
* when app loads an invalid token

you are right - something like this should be part of a boilerplate solution.

thanks for the feedback. and I wish you all the best with your project, and hope it goes well - it looks quite ambitious!

**Comment by hmuhdkamran** [comment]
it is very essential to have pop-up just like "https://github.com/stoodz/vuejsTimer.git", I have integrated like if the user click  on stay the token is updated with new expiry time.
second role based menu or features like 'https://aspnetboilerplate.com/Templates' would be beneficial. 
separate layout for login and logged-in pages.
unit test for vue components should be added, like karma i.e 'https://vuejs.org/v2/guide/unit-testing.html'
repository based db integration should be integrated, I have done it and happy to share.
