### ISSUE TITLE
fix issues with loading page

### ISSUE THREAD

**Issue by mrellipse** [mrellipse/toucan#8]
the loading page is not implemented correctly - it awaits the download of additional bundled resources before mounting app

**Comment by hmuhdkamran** [comment]
I am facing the same issue, I have tried lazy loading and split router, but still it take allot of time.

**Comment by mrellipse** [comment]
i did find a way to get the loading page working 100 % - i will try to find the time to check in the change in the coming week, so you can use it yourself :)

it builds on the approach using [HtmlWebpackPlugin](https://www.jonathan-petitcolas.com/2016/01/23/webpack-html-plugin-in-a-nutshell.html) here

once you have a list of all the assets you want to use (css and js), you can then run custom bootstrapping code to add dynamically add<script> and <style> elements to the page, and monitor their download progress

**Comment by mrellipse** [comment]
i have just pushed a commit for this loading issue. 

the basic production build (when combined with gzip compression) means client devices will download about 150kb (over half of that is shared resources) on their first request, which is pretty lean.

not quite as good as a progressive web app, but I am pretty happy with that result!

i don't know if this fix quite addresses your issues though - you mentioned trying async/lazy loading routes?

That isn't something i am looking at doing right now - but if you do come up with more optimized bundling & loading build, please do a pull request! Happy to merge something along those lines 👍
